out_dir: "sep-16/baseline_machine"
description: "baseline_machine from epoch 30"

cuda: 0
data_dir: "/storage/czw/rl_parser/data/1k_1_env_1_track_no_neg/"
dropout: 0.2 
hidden_size: 1000
num_epochs: 20
lr : !!float 1e-3
val_batch_size: 64

sort: False
train_batch_size: 8
ml_train_batch_size: 16
#types are beam, sample, and greedy
decode_mode: "sample"
#train types are iml, rl, ml
train_mode: "rl"
#only relevant for ml. should be False for everything else
teacher_force: True
#model types are auto_enc, enc_dec
#norm*, likelihood_only*, log*, accept, efficiency*
score_type: "accept"
#loss types are parse, gen, parse_gen. What goes into the loss function?
loss_type: "parse_gen"
train_split: 700
val_split: 150
checkpoint: True
valid_only: False
eval_only: False
baseline: 0.00
beam_width: 128
beta: 0.0
epsilon : !!float 0.15
planner_path: "ltl/craft_new_best_0708.pt"
curriculum_path: "curriculums/debug_curriculum.json"
alpha: "curriculum"

load_pretrained: False
pretrained: "sep-16/baseline_machine/checkpoint_30.pth"
load_pretrained_score_cache: False
load_pretrained_explore_cache: False
load_pretrained_length_cache: False
pickle_path: "jul-16/rl_parse/"
