out_dir: "may-31/ltl_supervised_no_negation"
description: "ltl full MLE supervision. no negation."

cuda: 0
data_dir: "/storage/czw/rl_parser/data/ltl_sparse_w_negation/"
dropout: 0.2 
hidden_size: 1000
num_epochs: 50
lr : !!float 1e-3
val_batch_size: 64

sort: False
train_batch_size: 16
ml_train_batch_size: 32
#types are beam, sample, and greedy
decode_mode: "greedy"
#train types are iml, rl, ml
train_mode: "ml"
#only relevant for ml. should be False for everything else
teacher_force: False
#model types are auto_enc, enc_dec
model_type: "enc_dec"
#score types are simulate, simulate_subset_pred, simulate_subset_obj
score_type: "simulate"
#loss types are parse, gen, parse_gen
loss_type: "parse"
train_split: 700
val_split: 150
checkpoint: False
valid_only: True
baseline: 0.00
beam_width: 1
beta: 0.0
epsilon : !!float 0.0
eval_only: True

load_pretrained: True
pretrained: "may-31/ltl_supervised_w_negation/best_checkpoint.pth"
load_pretrained_score_cache: False
load_pretrained_explore_cache: False
pickle_path: "may-29/debug/"
